---
  - ros_topic_name: "/rover_base2/cmd_vel"
    gz_topic_name: "cmd_vel"
    ros_type_name: "geometry_msgs/msg/Twist"
    gz_type_name: "ignition.msgs.Twist"
    direction: ROS_TO_GZ
  - ros_topic_name: "/keyboard/keypress"
    gz_topic_name: "/keyboard/keypress"
    ros_type_name: "std_msgs/msg/Int32"
    gz_type_name: "ignition.msgs.Int32"
    direction: GZ_TO_ROS
  - ros_topic_name: "/clock"
    gz_topic_name: "/clock"
    ros_type_name: "rosgraph_msgs/msg/Clock"
    gz_type_name: "ignition.msgs.Clock"
    direction: GZ_TO_ROS
  - ros_topic_name: "/rover_base2/odometry"
    gz_topic_name: "/model/rover_base2/odometry"
    ros_type_name: "nav_msgs/msg/Odometry"
    gz_type_name: "ignition.msgs.Odometry"
    direction: GZ_TO_ROS
  - ros_topic_name: "/rover_base2/scan"
    gz_topic_name: "/scan"
    ros_type_name: "sensor_msgs/msg/LaserScan"
    gz_type_name: "ignition.msgs.LaserScan"
    direction: GZ_TO_ROS
  - ros_topic_name: "/clock"
    gz_topic_name: "/clock"
    ros_type_name: "rosgraph_msgs/msg/clock"
    gz_type_name: "ignition.msgs.Clock"
    direction: GZ_TO_ROS
  - ros_topic_name: "/joint_states"
    gz_topic_name: "/world/demo/model/rover_base2/joint_state"
    ros_type_name: "sensor_msgs/msg/JointState"
    gz_type_name: "ignition.msgs.Model"
    direction: GZ_TO_ROS
  - ros_topic_name: "/tf"
    gz_topic_name: "/model/rover_base2/pose"
    ros_type_name: "tf2_msgs/msg/TFMessage"
    gz_type_name: "ignition.msgs.Pose_V"
    direction: GZ_TO_ROS
  - ros_topic_name: "/tf_static"
    gz_topic_name: "/model/rover_base2/pose_static"
    ros_type_name: "tf2_msgs/msg/TFMessage"
    gz_type_name: "ignition.msgs.Pose_V"
    direction: GZ_TO_ROS
  - ros_topic_name: "/imu"
    gz_topic_name: "/imu"
    ros_type_name: "sensor_msgs/msg/Imu"
    gz_type_name: "ignition.msgs.IMU"
    direction: GZ_TO_ROS
  - ros_topic_name: "/gpu_lidar"
    gz_topic_name: "/gpu_lidar"
    ros_type_name: "sensor_msgs/msg/LaserScan"
    gz_type_name: "ignition.msgs.LaserScan"
  - ros_topic_name: "/scan"
    gz_topic_name: "/gpu_lidar"
    ros_type_name: "sensor_msgs/msg/LaserScan"
    gz_type_name: "ignition.msgs.LaserScan"
    direction: GZ_TO_ROS
  - ros_topic_name: "/gpu_lidar_points"
    gz_topic_name: "/gpu_lidar/points"
    ros_type_name: "sensor_msgs/msg/PointCloud2"
    gz_type_name: "ignition.msgs.PointCloudPacked"
    direction: GZ_TO_ROS
  - ros_topic_name: "/camera_front"
    gz_topic_name: "/camera_front"
    ros_type_name: "sensor_msgs/msg/Image"
    gz_type_name: "ignition.msgs.Image"
    direction: GZ_TO_ROS
  - ros_topic_name: "/camera_front/points"
    gz_topic_name: "/camera_front/points"
    ros_type_name: "sensor_msgs/msg/PointCloud2"
    gz_type_name: "ignition.msgs.PointCloudPacked"
    direction: GZ_TO_ROS